<?php
date_default_timezone_set('America/Los_Angeles');
$local_time_zone_factor = trim(date('O', strtotime("now")), "-0");
global $now;
$now = time();
require('wp/wp-blog-header.php');
?>
<!DOCTYPE html><html><head><title>SF-Eagle Gay Bar | 398 12th Street</title><meta http-equiv="Content-Type" content="text/html" charset="utf-8"><!-- <META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">--><meta name="viewport" content="width=device-width"><meta name="viewport" content="initial-scale=1.0"><!--link(rel='stylesheet', href='css/wp.css')--><link rel="stylesheet" href="css/main.css.1374302189"><link href="http://fonts.googleapis.com/css?family=Jolly+Lodger|Coming+Soon|Rouge+Script" rel="stylesheet" type="text/css"><link rel="apple-touch-icon" href="images/icons/touch-icon-iphone-57x57.png"><link rel="apple-touch-icon" sizes="72x72" href="images/icons/touch-icon-ipad.png"><link rel="apple-touch-icon" sizes="114x114" href="images/icons/touch-icon-iphone-retina.png"><link rel="apple-touch-icon" sizes="144x144" href="images/icons/touch-icon-ipad-retina.png"><script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-42163204-1', 'sf-eagle.com');
ga('send', 'pageview');</script></head><body><!-- hello --><div id="background"></div><div id="page" class="simple merch"><a href="index.php"><img src="images/logo-transparency-whiteeagle-cutout-thumb.png" alt="logo" class="logo"></a><section><header class="cf"><h1>Hoodies Tanks & Tees</h1></header><article><div class="samples"><img src="images/merch/tee-red-front.jpg" alt="Red T-Shirt (front)"><img src="images/merch/tank-white-front.jpg" alt="White Tanktop (front)"><img src="images/merch/tank-gray-front.jpg" alt="Gray Tanktop (front)"><img src="images/merch/hoodie-gray-front.jpg" alt="Gray Hoodie (front)"><img src="images/merch/hoodie-gray-back.jpg" alt="Gray Hoodie (back)"><img src="images/merch/hoodie-black-front.jpg" alt="Black Hoodie (front)"><img src="images/merch/hoodie-black-back.jpg" alt="Black Hoodie (back)"><div id="hoodiequality">Hoodies are 80% cotton / 20% polyester<br>Beautiful and built to last<br><br>... models not included ...</div></div><table><tr><td><form action="merch-email.html" method="get"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="NFJKF939UUQT2"><table><tr><td><input type="hidden" name="on0" value="ITEMS">CHOOSE YOUR MAKE AND MODEL<br>all prices in U.S. dollars</td></tr><tr><td><select name="os0"><option value="T-SHIRT-BLACK">T-SHIRT (black) $18.00</option><option value="T-SHIRT-RED">T-SHIRT (red) $25.00</option><option value="T-SHIRT-LONG-SLEEVE">LONG SLEEVE T (black: not shown) $30.00</option><option value="TANKTOP-WHITE">TANKTOP (white) $25.00</option><option value="TANKTOP-GRAY">TANKTOP (gray) $25.00</option><option value="HOODIE-GRAY">HOODIE (gray) $55.00</option><option value="HOODIE-BLACK">HOODIE (black) $55.00</option></select></td></tr><tr><td><input type="hidden" name="on1" value="SIZE">SIZE</td></tr><tr><td><select name="os1"><option value="XXL">XXL</option><option value="XL">XL</option><option value="L">L</option><option value="M">M</option><option value="S">S</option></select></td></tr><tr><td><input type="hidden" name="currency_code" value="USD"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" name="submit" alt="PayPal - The safer, easier way to pay online!"></td></tr><tr><td><p>*shipping rate applies within the continental U.S. only - International rate will vary please email info@sf-eagle.com for information</p><p><a href="policy.html">return policy | privacy policy</a></p><a href="merch-email.html"></a></td></tr></table></form></td></tr></table></article></section></div><script src="widgets/lightbox/js/jquery-1.7.2.min.js"></script><script src="widgets/lightbox/js/lightbox-ck.js"></script><script src="widgets/flexslider/jquery.flexslider-ck.js"></script><script src="js/main.js.1374290986"></script></body></html>
