<!--
	<a href="http://www.sfbg.com/2011/06/28/girls-just-want-have-fun"><img class="flyer" src="pics/events/IMSL ShEagle April 17, 2013-800x612.jpg"></a>
      	<a href="pics/events/ShEagle-lite.jpg"><img src="pics/events/ShEagle-lite.jpg" /></a>
-->

<div class="flexslider">
  <ul class="slides">
    	<li>
	<p class="rc">Thursday</p>
      	<a href="pics/events/TNL-lite.jpg" rel="lightbox"><img src="pics/events/TNL-lite.jpg" /></a>
      	</li>
        <li>
	<p class="rc">Monday, May 20</p>
    <a href="pics/events/TorcheNov2011CLR-177-lite.jpg" rel="lightbox"><img src="pics/events/TorcheNov2011CLR-177-lite.jpg" /></a>
    	</li>
	<li>
	<p class="rc">YES! They're coming.</p>
      	<a href="pics/events/torche-poster-flat-lite.jpg" rel="lightbox"><img src="pics/events/torche-poster-flat-lite.jpg" /></a>
    	</li>
	<li>
	<p class="rc">Every 3rd Friday</p>
      	<a href="pics/events/CBHS_Poster-lite.jpg" rel="lightbox"><img src="pics/events/CBHS_Poster-lite.jpg" /></a>
    	</li>
	<li>
	<p class="rc">Friday Cigar Nights</p>
      	<a href="pics/events/cigar-lite.jpg" rel="lightbox"><img src="pics/events/cigar-lite.jpg" /></a>
    	</li>
    	<li>
	<p class="rc">Every 2nd and 4th Saturday</p>
      	<a href="pics/events/sadistic-lite.jpg" rel="lightbox"><img src="pics/events/sadistic-lite.jpg" /></a>
    	</li>
    	<li>
	<p class="rc">Every 2nd Sunday</p>
      	<a href="pics/events/rubber-showtunes-lite.jpg" rel="lightbox"><img src="pics/events/rubber-showtunes-lite.jpg" /></a>
    	</li>
    	<li>
  <p class="rc">Every 3rd Saturday</p>
    <a href="pics/events/bluf-lite.jpg" rel="lightbox"><img src="pics/events/bluf-lite.jpg" /></a>
    </li>
  </ul>
</div>
<div class="nonFlexslider">
  <ul class="slides">
    	<li>
	<p class="rc">Monday, May 20</p>
    <a href="pics/events/TorcheNov2011CLR-177-lite.jpg"><img src="pics/events/TorcheNov2011CLR-177-lite.jpg" /></a>
    	</li>
	<li>
	<p class="rc">Friday, May 24</p>
    <a href="pics/events/flag1-lite.jpg"><img src="pics/events/flag1-lite.jpg" /></a>
    	</li>
	<li>
	<p class="rc">YES! They're coming.</p>
      	<a href="pics/events/torche-poster-flat-lite.jpg"><img src="pics/events/torche-poster-flat-lite.jpg" /></a>
    	</li>
	<li>
	<p class="rc">Thursday</p>
      	<a href="pics/events/TNL-lite.jpg"><img src="pics/events/TNL-lite.jpg" /></a>
      	</li>
        <li>
	<p class="rc">Every 3rd Friday</p>
      	<a href="pics/events/CBHS_Poster-lite.jpg"><img src="pics/events/CBHS_Poster-lite.jpg" /></a>
    	</li>
	<li>
	<p class="rc">Friday Cigar Nights</p>
      	<a href="pics/events/cigar-lite.jpg"><img src="pics/events/cigar-lite.jpg" /></a>
    	</li>
    	<li>
	<p class="rc">Every 2nd and 4th Saturday</p>
      	<a href="pics/events/sadistic-lite.jpg"><img src="pics/events/sadistic-lite.jpg" /></a>
    	</li>
    	<li>
	<p class="rc">Every 2nd Sunday</p>
      	<a href="pics/events/rubber-showtunes-lite.jpg"><img src="pics/events/rubber-showtunes-lite.jpg" /></a>
    	</li>
    	<li>
  <p class="rc">Every 3rd Saturday</p>
    <a href="pics/events/bluf-lite.jpg"><img src="pics/events/bluf-lite.jpg" /></a>
    </li>
  </ul>
</div>

<!-- vim:ft=html:
-->
